// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: grpcd/service.proto

package grpcdconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	protos "github.com/grpcd/protos"
	sync "sync"
)

const (
	// GRPCDServiceName is the fully-qualified name of the GRPCDService service.
	GRPCDServiceName = "grpcd.GRPCDService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GRPCDServiceRegisterProcedure is the procedure name of the GRPCDService's Register RPC.
	GRPCDServiceRegisterProcedure = "/grpcd.GRPCDService/Register"
	// GRPCDServiceDiscoverProcedure is the procedure name of the GRPCDService's Discover RPC.
	GRPCDServiceDiscoverProcedure = "/grpcd.GRPCDService/Discover"
	// GRPCDServiceWatchProcedure is the procedure name of the GRPCDService's Watch RPC.
	GRPCDServiceWatchProcedure = "/grpcd.GRPCDService/Watch"
)

var (
	gRPCDServiceRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeServer,
			Schema:     protos.File_grpcd_service_proto.Services().ByName("GRPCDService").Methods().ByName("Register"),
			Procedure:  GRPCDServiceRegisterProcedure,
		}
	})
	gRPCDServiceDiscoverSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeBidi,
			Schema:     protos.File_grpcd_service_proto.Services().ByName("GRPCDService").Methods().ByName("Discover"),
			Procedure:  GRPCDServiceDiscoverProcedure,
		}
	})
	gRPCDServiceWatchSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeServer,
			Schema:     protos.File_grpcd_service_proto.Services().ByName("GRPCDService").Methods().ByName("Watch"),
			Procedure:  GRPCDServiceWatchProcedure,
		}
	})
)

// GRPCDServiceClient is a client for the grpcd.GRPCDService service.
type GRPCDServiceClient interface {
	// Register a service instance with its methods and hold the stream.
	Register(context.Context, *protos.RegisterRequest) (GRPCDServiceRegisterClientStream, error)
	// Discover addresses for a method, one candidate at a time.
	Discover(context.Context) (GRPCDServiceDiscoverClientStream, error)
	// Hold an address for a method and be told when to move to another.
	Watch(context.Context, *protos.WatchRequest) (GRPCDServiceWatchClientStream, error)
}

// NewGRPCDServiceClient constructs a client for the grpcd.GRPCDService service. Multiple service
// clients may share a single connect.Client.
func NewGRPCDServiceClient(client *connect.Client) GRPCDServiceClient {
	return &gRPCDServiceClient{client: client}
}

// GRPCDServiceRegisterClientStream is the client stream for the GRPCDService's Register RPC.
type GRPCDServiceRegisterClientStream struct {
	stream connect.ClientStream
}

// Receive returns the next response message from the server.
func (s GRPCDServiceRegisterClientStream) Receive() (*protos.RegisterResponse, error) {
	var res protos.RegisterResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s GRPCDServiceRegisterClientStream) Close() error {
	return s.stream.Close()
}

// GRPCDServiceDiscoverClientStream is the client stream for the GRPCDService's Discover RPC.
type GRPCDServiceDiscoverClientStream struct {
	stream connect.ClientStream
}

// SendHeaders opens the stream and flushes the request headers without a message. The first Send or
// Receive does this implicitly.
func (s GRPCDServiceDiscoverClientStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a request message to the server.
func (s GRPCDServiceDiscoverClientStream) Send(req *protos.DiscoverRequest) error {
	return s.stream.Send(req)
}

// CloseSend closes the request side of the stream.
func (s GRPCDServiceDiscoverClientStream) CloseSend() error {
	return s.stream.CloseSend()
}

// Receive returns the next response message from the server.
func (s GRPCDServiceDiscoverClientStream) Receive() (*protos.DiscoverResponse, error) {
	var res protos.DiscoverResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s GRPCDServiceDiscoverClientStream) Close() error {
	return s.stream.Close()
}

// GRPCDServiceWatchClientStream is the client stream for the GRPCDService's Watch RPC.
type GRPCDServiceWatchClientStream struct {
	stream connect.ClientStream
}

// Receive returns the next response message from the server.
func (s GRPCDServiceWatchClientStream) Receive() (*protos.WatchResponse, error) {
	var res protos.WatchResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s GRPCDServiceWatchClientStream) Close() error {
	return s.stream.Close()
}

// GRPCDServiceHandler is an implementation of the grpcd.GRPCDService service.
type GRPCDServiceHandler interface {
	// Register a service instance with its methods and hold the stream.
	Register(context.Context, *protos.RegisterRequest, GRPCDServiceRegisterServerStream) error
	// Discover addresses for a method, one candidate at a time.
	Discover(context.Context, GRPCDServiceDiscoverServerStream) error
	// Hold an address for a method and be told when to move to another.
	Watch(context.Context, *protos.WatchRequest, GRPCDServiceWatchServerStream) error
}

// RegisterGRPCDServiceHandler registers svc as the grpcd.GRPCDService implementation on server.
func RegisterGRPCDServiceHandler(server *connect.Server, svc GRPCDServiceHandler) {
	adapter := gRPCDServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: gRPCDServiceRegisterSpec(), Handler: adapter.register},
		connect.Method{Spec: gRPCDServiceDiscoverSpec(), Handler: adapter.discover},
		connect.Method{Spec: gRPCDServiceWatchSpec(), Handler: adapter.watch},
	)
}

// GRPCDServiceRegisterServerStream is the server stream for the GRPCDService's Register RPC.
type GRPCDServiceRegisterServerStream struct {
	stream connect.ServerStream
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s GRPCDServiceRegisterServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s GRPCDServiceRegisterServerStream) Send(res *protos.RegisterResponse) error {
	return s.stream.Send(res)
}

// GRPCDServiceDiscoverServerStream is the server stream for the GRPCDService's Discover RPC.
type GRPCDServiceDiscoverServerStream struct {
	stream connect.ServerStream
}

// Receive returns the next request message from the client.
func (s GRPCDServiceDiscoverServerStream) Receive() (*protos.DiscoverRequest, error) {
	var req protos.DiscoverRequest
	if err := s.stream.Receive(&req); err != nil {
		return nil, err
	}
	return &req, nil
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s GRPCDServiceDiscoverServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s GRPCDServiceDiscoverServerStream) Send(res *protos.DiscoverResponse) error {
	return s.stream.Send(res)
}

// GRPCDServiceWatchServerStream is the server stream for the GRPCDService's Watch RPC.
type GRPCDServiceWatchServerStream struct {
	stream connect.ServerStream
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s GRPCDServiceWatchServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s GRPCDServiceWatchServerStream) Send(res *protos.WatchResponse) error {
	return s.stream.Send(res)
}

// UnimplementedGRPCDServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGRPCDServiceHandler struct{}

func (UnimplementedGRPCDServiceHandler) Register(context.Context, *protos.RegisterRequest, GRPCDServiceRegisterServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "grpcd.GRPCDService.Register is not implemented")
}

func (UnimplementedGRPCDServiceHandler) Discover(context.Context, GRPCDServiceDiscoverServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "grpcd.GRPCDService.Discover is not implemented")
}

func (UnimplementedGRPCDServiceHandler) Watch(context.Context, *protos.WatchRequest, GRPCDServiceWatchServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "grpcd.GRPCDService.Watch is not implemented")
}

type gRPCDServiceClient struct {
	client *connect.Client
}

func (c *gRPCDServiceClient) Register(ctx context.Context, req *protos.RegisterRequest) (GRPCDServiceRegisterClientStream, error) {
	stream, err := c.client.CallServerStream(ctx, gRPCDServiceRegisterSpec(), req)
	if err != nil {
		return GRPCDServiceRegisterClientStream{}, err
	}
	return GRPCDServiceRegisterClientStream{stream: stream}, nil
}

func (c *gRPCDServiceClient) Discover(ctx context.Context) (GRPCDServiceDiscoverClientStream, error) {
	stream, err := c.client.CallClientStream(ctx, gRPCDServiceDiscoverSpec())
	if err != nil {
		return GRPCDServiceDiscoverClientStream{}, err
	}
	return GRPCDServiceDiscoverClientStream{stream: stream}, nil
}

func (c *gRPCDServiceClient) Watch(ctx context.Context, req *protos.WatchRequest) (GRPCDServiceWatchClientStream, error) {
	stream, err := c.client.CallServerStream(ctx, gRPCDServiceWatchSpec(), req)
	if err != nil {
		return GRPCDServiceWatchClientStream{}, err
	}
	return GRPCDServiceWatchClientStream{stream: stream}, nil
}

type gRPCDServiceHandler struct{ svc GRPCDServiceHandler }

func (h gRPCDServiceHandler) register(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req protos.RegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	return h.svc.Register(ctx, &req, GRPCDServiceRegisterServerStream{stream: stream})
}

func (h gRPCDServiceHandler) discover(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	return h.svc.Discover(ctx, GRPCDServiceDiscoverServerStream{stream: stream})
}

func (h gRPCDServiceHandler) watch(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req protos.WatchRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	return h.svc.Watch(ctx, &req, GRPCDServiceWatchServerStream{stream: stream})
}
